DROP POLICY IF EXISTS "Public select for products" ON public.products;
DROP POLICY IF EXISTS "Public insert for products" ON public.products;
DROP POLICY IF EXISTS "Public update for products" ON public.products;
DROP POLICY IF EXISTS "Public delete for products" ON public.products;
DROP POLICY IF EXISTS "Public select for customers" ON public.customers;
DROP POLICY IF EXISTS "Public insert for customers" ON public.customers;
DROP POLICY IF EXISTS "Public update for customers" ON public.customers;
DROP POLICY IF EXISTS "Public delete for customers" ON public.customers;
DROP POLICY IF EXISTS "Public select for sales" ON public.sales;
DROP POLICY IF EXISTS "Public insert for sales" ON public.sales;
DROP POLICY IF EXISTS "Public update for sales" ON public.sales;
DROP POLICY IF EXISTS "Public delete for sales" ON public.sales;
DROP POLICY IF EXISTS "Public select for sale_items" ON public.sale_items;
DROP POLICY IF EXISTS "Public insert for sale_items" ON public.sale_items;
DROP POLICY IF EXISTS "Public update for sale_items" ON public.sale_items;
DROP POLICY IF EXISTS "Public delete for sale_items" ON public.sale_items;
DROP POLICY IF EXISTS "Public select for purchases" ON public.purchases;
DROP POLICY IF EXISTS "Public insert for purchases" ON public.purchases;
DROP POLICY IF EXISTS "Public update for purchases" ON public.purchases;
DROP POLICY IF EXISTS "Public delete for purchases" ON public.purchases;
DROP POLICY IF EXISTS "Public select for cash_flow" ON public.cash_flow;
DROP POLICY IF EXISTS "Public insert for cash_flow" ON public.cash_flow;
DROP POLICY IF EXISTS "Public update for cash_flow" ON public.cash_flow;
DROP POLICY IF EXISTS "Public delete for cash_flow" ON public.cash_flow;
DROP POLICY IF EXISTS "Public select for bills" ON public.bills;
DROP POLICY IF EXISTS "Public insert for bills" ON public.bills;
DROP POLICY IF EXISTS "Public update for bills" ON public.bills;
DROP POLICY IF EXISTS "Public delete for bills" ON public.bills;
DROP POLICY IF EXISTS "Public select for purchase_batches" ON public.purchase_batches;
DROP POLICY IF EXISTS "Public insert for purchase_batches" ON public.purchase_batches;
DROP POLICY IF EXISTS "Public update for purchase_batches" ON public.purchase_batches;
DROP POLICY IF EXISTS "Public delete for purchase_batches" ON public.purchase_batches;
DROP POLICY IF EXISTS "Public select for inventory_movements" ON public.inventory_movements;
DROP POLICY IF EXISTS "Public insert for inventory_movements" ON public.inventory_movements;
DROP POLICY IF EXISTS "Public select for app_settings" ON public.app_settings;
DROP POLICY IF EXISTS "Public insert for app_settings" ON public.app_settings;
DROP POLICY IF EXISTS "Public update for app_settings" ON public.app_settings;
DROP POLICY IF EXISTS "Public delete for app_settings" ON public.app_settings;

CREATE POLICY "Auth select for products" ON public.products FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert for products" ON public.products FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update for products" ON public.products FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth delete for products" ON public.products FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth select for customers" ON public.customers FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert for customers" ON public.customers FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update for customers" ON public.customers FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth delete for customers" ON public.customers FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth select for sales" ON public.sales FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert for sales" ON public.sales FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update for sales" ON public.sales FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth delete for sales" ON public.sales FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth select for sale_items" ON public.sale_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert for sale_items" ON public.sale_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update for sale_items" ON public.sale_items FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth delete for sale_items" ON public.sale_items FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth select for purchases" ON public.purchases FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert for purchases" ON public.purchases FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update for purchases" ON public.purchases FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth delete for purchases" ON public.purchases FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth select for cash_flow" ON public.cash_flow FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert for cash_flow" ON public.cash_flow FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update for cash_flow" ON public.cash_flow FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth delete for cash_flow" ON public.cash_flow FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth select for bills" ON public.bills FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert for bills" ON public.bills FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update for bills" ON public.bills FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth delete for bills" ON public.bills FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth select for purchase_batches" ON public.purchase_batches FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert for purchase_batches" ON public.purchase_batches FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update for purchase_batches" ON public.purchase_batches FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth delete for purchase_batches" ON public.purchase_batches FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth select for inventory_movements" ON public.inventory_movements FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert for inventory_movements" ON public.inventory_movements FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth select for app_settings" ON public.app_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert for app_settings" ON public.app_settings FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update for app_settings" ON public.app_settings FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth delete for app_settings" ON public.app_settings FOR DELETE TO authenticated USING (true);